# Generated by Django 4.2.6 on 2023-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='photo',
            field=models.FileField(default='posts/download.png', upload_to='posts/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='summary',
            field=models.TextField(default='example'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='example', max_length=100),
        ),
    ]
