# Generated by Django 4.2.6 on 2023-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='summary',
            field=models.TextField(),
        ),
    ]
