# Generated by Django 4.2.6 on 2023-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemodel',
            name='certificate',
            field=models.FileField(default='portfolio/sample.pdf', upload_to='certificates/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='name',
            field=models.CharField(default='example', max_length=150),
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='short',
            field=models.CharField(default='short', max_length=100),
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='title',
            field=models.CharField(default='tv', max_length=100),
        ),
        migrations.AddField(
            model_name='tvmodel',
            name='video',
            field=models.CharField(default='video', max_length=500),
        ),
    ]
