# Generated by Django 4.2.6 on 2023-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificatemodel_certificate_certificatemodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatemodel',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='short',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
