# Generated by Django 4.2.6 on 2023-10-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_certificatemodel_name_alter_tvmodel_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyermodel',
            name='Extract',
            field=models.CharField(default='default', max_length=150),
        ),
    ]
