# Generated by Django 4.2.6 on 2023-10-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_certificate_certificatemodel_certificate_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatemodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='certificate_link',
            field=models.ImageField(default='portfolio/sample.pdf', upload_to='certificates/%y/%m/%d/'),
        ),
    ]
