# Generated by Django 4.2.6 on 2023-10-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_helpmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelpModel',
            new_name='ContactModel',
        ),
    ]
