# Generated by Django 4.2.6 on 2023-10-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_helpmodel_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyermodel',
            name='quote',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
